name: 'Add px4 releases to monday'
description: 'Add px4 releases to monday'
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  url:
    required: true
  tag:
    required: true
  token:
    description: 'Monday authentication token to use'
    required: true
  board-id:
    required: true
  group:
    required: true
  link-column:
    required: true
  date-column:
    required: true
outputs:
  item-id: 
    description: ''
runs:
  using: 'node12'
  main: 'index.js'
